### ISSUE TITLE
Up/Down Vote sprite sheet not working

### ISSUE THREAD

**Issue by Fuzzylog1cza** [adderlan/reddit.sea#2]
Something is up with the sprite sheet. Hi-lighting green in the preview, and I'm a bit nervous of taking it live without testing. I'd like to dig a bit further into it.
- Remember no need to fix these yourself. I've forked the repo and will make the changes with a pull request unless you grant me contribution access.

**Comment by adderlan** [comment]
I'm not sure what you mean by "Hi-lighting green in the preview". I _think_ it's a background-position problem?

But yeah, you shouldn't take it live until tested, but Reddit doesn't give you a lot of options for that. I couldn't even create a subreddit for testing because I don't have enough 'karma', but that will have to happen eventually as I can't think of any other way to safely test this.

**Comment by Fuzzylog1cza** [comment]
Let me have a go, the green is probably a fail in the transparency layer on reddit.

**Comment by Fuzzylog1cza** [comment]
Resolved, please accept merge request.
